// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tendermint/types/work.proto

package types

import (
	encoding_binary "encoding/binary"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/gogo/protobuf/types"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Work struct {
	// Types that are valid to be assigned to Sum:
	//	*Work_FloatWork
	//	*Work_StringWork
	Sum isWork_Sum `protobuf_oneof:"sum"`
}

func (m *Work) Reset()         { *m = Work{} }
func (m *Work) String() string { return proto.CompactTextString(m) }
func (*Work) ProtoMessage()    {}
func (*Work) Descriptor() ([]byte, []int) {
	return fileDescriptor_7fa7c0758235f145, []int{0}
}
func (m *Work) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Work) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Work.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Work) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Work.Merge(m, src)
}
func (m *Work) XXX_Size() int {
	return m.Size()
}
func (m *Work) XXX_DiscardUnknown() {
	xxx_messageInfo_Work.DiscardUnknown(m)
}

var xxx_messageInfo_Work proto.InternalMessageInfo

type isWork_Sum interface {
	isWork_Sum()
	MarshalTo([]byte) (int, error)
	Size() int
}

type Work_FloatWork struct {
	FloatWork *FloatWork `protobuf:"bytes,1,opt,name=float_work,json=floatWork,proto3,oneof" json:"float_work,omitempty"`
}
type Work_StringWork struct {
	StringWork *StringWork `protobuf:"bytes,2,opt,name=string_work,json=stringWork,proto3,oneof" json:"string_work,omitempty"`
}

func (*Work_FloatWork) isWork_Sum()  {}
func (*Work_StringWork) isWork_Sum() {}

func (m *Work) GetSum() isWork_Sum {
	if m != nil {
		return m.Sum
	}
	return nil
}

func (m *Work) GetFloatWork() *FloatWork {
	if x, ok := m.GetSum().(*Work_FloatWork); ok {
		return x.FloatWork
	}
	return nil
}

func (m *Work) GetStringWork() *StringWork {
	if x, ok := m.GetSum().(*Work_StringWork); ok {
		return x.StringWork
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Work) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Work_FloatWork)(nil),
		(*Work_StringWork)(nil),
	}
}

// FloatWork designed for works that are not designed to return a number in
// response to the problem.
type FloatWork struct {
	Db        float64   `protobuf:"fixed64,1,opt,name=db,proto3" json:"db,omitempty"`
	Location  float64   `protobuf:"fixed64,2,opt,name=location,proto3" json:"location,omitempty"`
	Lengh     float64   `protobuf:"fixed64,3,opt,name=lengh,proto3" json:"lengh,omitempty"`
	Solution  float64   `protobuf:"fixed64,4,opt,name=solution,proto3" json:"solution,omitempty"`
	Timestamp time.Time `protobuf:"bytes,5,opt,name=timestamp,proto3,stdtime" json:"timestamp"`
}

func (m *FloatWork) Reset()         { *m = FloatWork{} }
func (m *FloatWork) String() string { return proto.CompactTextString(m) }
func (*FloatWork) ProtoMessage()    {}
func (*FloatWork) Descriptor() ([]byte, []int) {
	return fileDescriptor_7fa7c0758235f145, []int{1}
}
func (m *FloatWork) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FloatWork) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FloatWork.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FloatWork) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FloatWork.Merge(m, src)
}
func (m *FloatWork) XXX_Size() int {
	return m.Size()
}
func (m *FloatWork) XXX_DiscardUnknown() {
	xxx_messageInfo_FloatWork.DiscardUnknown(m)
}

var xxx_messageInfo_FloatWork proto.InternalMessageInfo

func (m *FloatWork) GetDb() float64 {
	if m != nil {
		return m.Db
	}
	return 0
}

func (m *FloatWork) GetLocation() float64 {
	if m != nil {
		return m.Location
	}
	return 0
}

func (m *FloatWork) GetLengh() float64 {
	if m != nil {
		return m.Lengh
	}
	return 0
}

func (m *FloatWork) GetSolution() float64 {
	if m != nil {
		return m.Solution
	}
	return 0
}

func (m *FloatWork) GetTimestamp() time.Time {
	if m != nil {
		return m.Timestamp
	}
	return time.Time{}
}

// StringWork designed for works that are not designed to return string in
// response to the problem.
type StringWork struct {
	Db        float64   `protobuf:"fixed64,1,opt,name=db,proto3" json:"db,omitempty"`
	Location  float64   `protobuf:"fixed64,2,opt,name=location,proto3" json:"location,omitempty"`
	Lengh     float64   `protobuf:"fixed64,3,opt,name=lengh,proto3" json:"lengh,omitempty"`
	Solution  string    `protobuf:"bytes,4,opt,name=solution,proto3" json:"solution,omitempty"`
	Timestamp time.Time `protobuf:"bytes,5,opt,name=timestamp,proto3,stdtime" json:"timestamp"`
}

func (m *StringWork) Reset()         { *m = StringWork{} }
func (m *StringWork) String() string { return proto.CompactTextString(m) }
func (*StringWork) ProtoMessage()    {}
func (*StringWork) Descriptor() ([]byte, []int) {
	return fileDescriptor_7fa7c0758235f145, []int{2}
}
func (m *StringWork) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StringWork) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StringWork.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StringWork) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringWork.Merge(m, src)
}
func (m *StringWork) XXX_Size() int {
	return m.Size()
}
func (m *StringWork) XXX_DiscardUnknown() {
	xxx_messageInfo_StringWork.DiscardUnknown(m)
}

var xxx_messageInfo_StringWork proto.InternalMessageInfo

func (m *StringWork) GetDb() float64 {
	if m != nil {
		return m.Db
	}
	return 0
}

func (m *StringWork) GetLocation() float64 {
	if m != nil {
		return m.Location
	}
	return 0
}

func (m *StringWork) GetLengh() float64 {
	if m != nil {
		return m.Lengh
	}
	return 0
}

func (m *StringWork) GetSolution() string {
	if m != nil {
		return m.Solution
	}
	return ""
}

func (m *StringWork) GetTimestamp() time.Time {
	if m != nil {
		return m.Timestamp
	}
	return time.Time{}
}

type WorkList struct {
	Work []Work `protobuf:"bytes,1,rep,name=work,proto3" json:"work"`
}

func (m *WorkList) Reset()         { *m = WorkList{} }
func (m *WorkList) String() string { return proto.CompactTextString(m) }
func (*WorkList) ProtoMessage()    {}
func (*WorkList) Descriptor() ([]byte, []int) {
	return fileDescriptor_7fa7c0758235f145, []int{3}
}
func (m *WorkList) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *WorkList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_WorkList.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *WorkList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkList.Merge(m, src)
}
func (m *WorkList) XXX_Size() int {
	return m.Size()
}
func (m *WorkList) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkList.DiscardUnknown(m)
}

var xxx_messageInfo_WorkList proto.InternalMessageInfo

func (m *WorkList) GetWork() []Work {
	if m != nil {
		return m.Work
	}
	return nil
}

func init() {
	proto.RegisterType((*Work)(nil), "tendermint.types.Work")
	proto.RegisterType((*FloatWork)(nil), "tendermint.types.FloatWork")
	proto.RegisterType((*StringWork)(nil), "tendermint.types.StringWork")
	proto.RegisterType((*WorkList)(nil), "tendermint.types.WorkList")
}

func init() { proto.RegisterFile("tendermint/types/work.proto", fileDescriptor_7fa7c0758235f145) }

var fileDescriptor_7fa7c0758235f145 = []byte{
	// 393 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x52, 0x4d, 0x6b, 0xab, 0x40,
	0x14, 0x75, 0x12, 0xf3, 0x88, 0x37, 0xf0, 0x78, 0x0c, 0xe1, 0x11, 0x4c, 0x30, 0x21, 0xab, 0xac,
	0xc6, 0x47, 0xde, 0xa2, 0x9b, 0x40, 0xc1, 0x45, 0xe9, 0xa2, 0x9b, 0xda, 0x42, 0xa1, 0x9b, 0xa2,
	0xd1, 0x18, 0x89, 0x3a, 0x41, 0xc7, 0x96, 0xfe, 0x87, 0x2e, 0xf2, 0x47, 0xda, 0xdf, 0x91, 0x65,
	0x96, 0x5d, 0xb5, 0x25, 0xf9, 0x23, 0xc5, 0x19, 0x3f, 0x4a, 0xdc, 0xb6, 0x1b, 0xb9, 0xc7, 0x73,
	0x8e, 0xf7, 0x78, 0xef, 0x85, 0x3e, 0x73, 0x23, 0xc7, 0x8d, 0x43, 0x3f, 0x62, 0x3a, 0x7b, 0x5c,
	0xbb, 0x89, 0xfe, 0x40, 0xe3, 0x15, 0x59, 0xc7, 0x94, 0x51, 0xfc, 0xa7, 0x22, 0x09, 0x27, 0xd5,
	0xae, 0x47, 0x3d, 0xca, 0x49, 0x3d, 0xab, 0x84, 0x4e, 0x1d, 0x7a, 0x94, 0x7a, 0x81, 0xab, 0x73,
	0x64, 0xa7, 0x0b, 0x9d, 0xf9, 0xa1, 0x9b, 0x30, 0x2b, 0x5c, 0xe7, 0x82, 0x41, 0xad, 0x0b, 0x7f,
	0xe6, 0xec, 0xa8, 0xc6, 0xde, 0x5b, 0x81, 0xef, 0x58, 0x8c, 0xc6, 0x42, 0x31, 0x7e, 0x42, 0x20,
	0xdf, 0xd0, 0x78, 0x85, 0x67, 0x00, 0x8b, 0x80, 0x5a, 0xec, 0x2e, 0x4b, 0xd9, 0x43, 0x23, 0x34,
	0xe9, 0x4c, 0xfb, 0xe4, 0x38, 0x26, 0x39, 0xcb, 0x34, 0x99, 0xe1, 0x5c, 0x32, 0x95, 0x45, 0x01,
	0xf0, 0x29, 0x74, 0x12, 0x16, 0xfb, 0x91, 0x27, 0xec, 0x0d, 0x6e, 0x1f, 0xd4, 0xed, 0x57, 0x5c,
	0x94, 0xfb, 0x21, 0x29, 0x91, 0xd1, 0x82, 0x66, 0x92, 0x86, 0xe3, 0x67, 0x04, 0x4a, 0xd9, 0x02,
	0xff, 0x86, 0x86, 0x63, 0xf3, 0x2c, 0xc8, 0x6c, 0x38, 0x36, 0x56, 0xa1, 0x1d, 0xd0, 0xb9, 0xc5,
	0x7c, 0x1a, 0xf1, 0x16, 0xc8, 0x2c, 0x31, 0xee, 0x42, 0x2b, 0x70, 0x23, 0x6f, 0xd9, 0x6b, 0x72,
	0x42, 0x80, 0xcc, 0x91, 0xd0, 0x20, 0xe5, 0x0e, 0x59, 0x38, 0x0a, 0x8c, 0x0d, 0x50, 0xca, 0x69,
	0xf6, 0x5a, 0x3c, 0xb1, 0x4a, 0xc4, 0xbc, 0x49, 0x31, 0x6f, 0x72, 0x5d, 0x28, 0x8c, 0xf6, 0xf6,
	0x6d, 0x28, 0x6d, 0xde, 0x87, 0xc8, 0xac, 0x6c, 0xe3, 0x17, 0x04, 0x50, 0xfd, 0xd3, 0x0f, 0x04,
	0x56, 0xbe, 0x39, 0xf0, 0x0c, 0xda, 0x59, 0xd2, 0x0b, 0x3f, 0x61, 0xf8, 0x1f, 0xc8, 0xf9, 0xb2,
	0x9b, 0x93, 0xce, 0xf4, 0x6f, 0x7d, 0x5b, 0x7c, 0x33, 0x72, 0xf6, 0x19, 0x93, 0x2b, 0x8d, 0xcb,
	0xed, 0x5e, 0x43, 0xbb, 0xbd, 0x86, 0x3e, 0xf6, 0x1a, 0xda, 0x1c, 0x34, 0x69, 0x77, 0xd0, 0xa4,
	0xd7, 0x83, 0x26, 0xdd, 0x9e, 0x78, 0x3e, 0x5b, 0xa6, 0x36, 0x99, 0xd3, 0x50, 0xff, 0x7a, 0x74,
	0x55, 0x29, 0x6e, 0xfb, 0xf8, 0x20, 0xed, 0x5f, 0xfc, 0xfd, 0xff, 0xcf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x46, 0xbd, 0x16, 0x7f, 0x2f, 0x03, 0x00, 0x00,
}

func (m *Work) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Work) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Work) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Sum != nil {
		{
			size := m.Sum.Size()
			i -= size
			if _, err := m.Sum.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	return len(dAtA) - i, nil
}

func (m *Work_FloatWork) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Work_FloatWork) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.FloatWork != nil {
		{
			size, err := m.FloatWork.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintWork(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}
func (m *Work_StringWork) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Work_StringWork) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.StringWork != nil {
		{
			size, err := m.StringWork.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintWork(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}
func (m *FloatWork) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FloatWork) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FloatWork) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n3, err3 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.Timestamp, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.Timestamp):])
	if err3 != nil {
		return 0, err3
	}
	i -= n3
	i = encodeVarintWork(dAtA, i, uint64(n3))
	i--
	dAtA[i] = 0x2a
	if m.Solution != 0 {
		i -= 8
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.Solution))))
		i--
		dAtA[i] = 0x21
	}
	if m.Lengh != 0 {
		i -= 8
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.Lengh))))
		i--
		dAtA[i] = 0x19
	}
	if m.Location != 0 {
		i -= 8
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.Location))))
		i--
		dAtA[i] = 0x11
	}
	if m.Db != 0 {
		i -= 8
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.Db))))
		i--
		dAtA[i] = 0x9
	}
	return len(dAtA) - i, nil
}

func (m *StringWork) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StringWork) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StringWork) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n4, err4 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.Timestamp, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.Timestamp):])
	if err4 != nil {
		return 0, err4
	}
	i -= n4
	i = encodeVarintWork(dAtA, i, uint64(n4))
	i--
	dAtA[i] = 0x2a
	if len(m.Solution) > 0 {
		i -= len(m.Solution)
		copy(dAtA[i:], m.Solution)
		i = encodeVarintWork(dAtA, i, uint64(len(m.Solution)))
		i--
		dAtA[i] = 0x22
	}
	if m.Lengh != 0 {
		i -= 8
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.Lengh))))
		i--
		dAtA[i] = 0x19
	}
	if m.Location != 0 {
		i -= 8
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.Location))))
		i--
		dAtA[i] = 0x11
	}
	if m.Db != 0 {
		i -= 8
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.Db))))
		i--
		dAtA[i] = 0x9
	}
	return len(dAtA) - i, nil
}

func (m *WorkList) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WorkList) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *WorkList) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Work) > 0 {
		for iNdEx := len(m.Work) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Work[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintWork(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintWork(dAtA []byte, offset int, v uint64) int {
	offset -= sovWork(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Work) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Sum != nil {
		n += m.Sum.Size()
	}
	return n
}

func (m *Work_FloatWork) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.FloatWork != nil {
		l = m.FloatWork.Size()
		n += 1 + l + sovWork(uint64(l))
	}
	return n
}
func (m *Work_StringWork) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.StringWork != nil {
		l = m.StringWork.Size()
		n += 1 + l + sovWork(uint64(l))
	}
	return n
}
func (m *FloatWork) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Db != 0 {
		n += 9
	}
	if m.Location != 0 {
		n += 9
	}
	if m.Lengh != 0 {
		n += 9
	}
	if m.Solution != 0 {
		n += 9
	}
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.Timestamp)
	n += 1 + l + sovWork(uint64(l))
	return n
}

func (m *StringWork) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Db != 0 {
		n += 9
	}
	if m.Location != 0 {
		n += 9
	}
	if m.Lengh != 0 {
		n += 9
	}
	l = len(m.Solution)
	if l > 0 {
		n += 1 + l + sovWork(uint64(l))
	}
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.Timestamp)
	n += 1 + l + sovWork(uint64(l))
	return n
}

func (m *WorkList) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Work) > 0 {
		for _, e := range m.Work {
			l = e.Size()
			n += 1 + l + sovWork(uint64(l))
		}
	}
	return n
}

func sovWork(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozWork(x uint64) (n int) {
	return sovWork(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Work) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWork
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Work: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Work: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FloatWork", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWork
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWork
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthWork
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &FloatWork{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Sum = &Work_FloatWork{v}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StringWork", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWork
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWork
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthWork
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &StringWork{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Sum = &Work_StringWork{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipWork(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthWork
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FloatWork) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWork
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FloatWork: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FloatWork: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field Db", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.Db = float64(math.Float64frombits(v))
		case 2:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field Location", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.Location = float64(math.Float64frombits(v))
		case 3:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field Lengh", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.Lengh = float64(math.Float64frombits(v))
		case 4:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field Solution", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.Solution = float64(math.Float64frombits(v))
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWork
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWork
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthWork
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.Timestamp, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipWork(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthWork
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StringWork) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWork
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StringWork: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StringWork: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field Db", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.Db = float64(math.Float64frombits(v))
		case 2:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field Location", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.Location = float64(math.Float64frombits(v))
		case 3:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field Lengh", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.Lengh = float64(math.Float64frombits(v))
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Solution", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWork
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWork
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWork
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Solution = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWork
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWork
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthWork
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.Timestamp, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipWork(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthWork
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *WorkList) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWork
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WorkList: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WorkList: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Work", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWork
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWork
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthWork
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Work = append(m.Work, Work{})
			if err := m.Work[len(m.Work)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipWork(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthWork
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipWork(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowWork
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowWork
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowWork
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthWork
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupWork
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthWork
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthWork        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowWork          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupWork = fmt.Errorf("proto: unexpected end of group")
)
